### ISSUE TITLE
Concepts Insights - Getting error in using semanticSearch()

### ISSUE THREAD

**Issue by kajaldas007** [watson-developer-cloud/nodejs-wrapper#7] opened 2015-03-19 02:58 UTC
params used (in 2 attempts):
(a) var params = {user: '5d05b04f-84d3-4875-a1b8-924a18886cf5',
	  corpus: 'genome',
	  ids: 'miRNA'            // single string
     };
(b) var params = {user: '5d05b04f-84d3-4875-a1b8-924a18886cf5',
	  corpus: 'genome',
        ids: ['miRNA']              // array of strings
     };

Error text in both cases:
{ error: 'invalid ids parameter',
  url: '/5d05b04f-84d3-4875-a1b8-924a18886cf5/genome' }

**Comment by germanattanasio** [comment] 2015-03-19 15:11
duplicate of #10

**Closed by germanattanasio** 2015-03-19 15:11 UTC
