### ISSUE TITLE
Concepts Insights - Getting error in using getRelatedConcept()

### ISSUE THREAD

**Issue by kajaldas007** [watson-developer-cloud/nodejs-wrapper#6] opened 2015-03-19 02:56 UTC
params used in 2 attempts:
(a) var params = {user: '5d05b04f-84d3-4875-a1b8-924a18886cf5',
	                    graph: 'en-20120601',
	                    concepts: '/graph/wikipedia/en-20120601/miRNA'     // i.e. a string
     };
(b) var params = {user: '5d05b04f-84d3-4875-a1b8-924a18886cf5',
	                     graph: 'en-20120601',
	                     concepts: ['/graph/wikipedia/en-20120601/miRNA']    // an array of strings
     };

Error text in both cases:
{ error: 'invalid concepts parameter',
  url: '/5d05b04f-84d3-4875-a1b8-924a18886cf5/en-20120601' }

**Comment by germanattanasio** [comment] 2015-03-19 15:11
duplicate of #10

**Closed by germanattanasio** 2015-03-19 15:11 UTC
Labels: duplicate
